image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode" # -s .m2/settings.xml
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -s dev-files/settings.deploy.xml deploy
  only:
    - master

force-deploy:
  when: manual
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true -s dev-files/settings.deploy.xml deploy
