image: maven:latest

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the default branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags

variables:
  MAVEN_CLI_OPTS: "--batch-mode" # -s .m2/settings.xml
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS --fail-at-end verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml


deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -s dev-files/settings.deploy.xml deploy
  only:
    - master

force-deploy:
  when: manual
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true -s dev-files/settings.deploy.xml deploy
